name: Gerador de Mangá em PDF

on:
  workflow_dispatch:

jobs:
  build-and-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Instalar dependências do Sistema (Display Virtual)
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Instalar dependências do Python
        run: pip install -r requirements.txt

      - name: Executar o Scraper e Gerar PDF
        run: xvfb-run python gerar_manga.py

      - name: Salvar Resultados como Artefato
        uses: actions/upload-artifact@v4
        # always() força o GitHub a salvar os arquivos mesmo que o script dê Erro 1
        if: always() 
        with:
          name: manga-resultados
          # Salva o PDF e o Print de erro (se existir)
          path: |
            *.pdf
            *.png
          retention-days: 7